### ISSUE TITLE
Errors in console when loading map saved where only detail panel has been replaced by 3D scatterplot

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/NG-CHM#258]
To reproduce:
Open deprez1000 map.
Replace detail panel with 3D Scatterplot (Accept defaults for scatterplot)
Save Map
Load saved map
In console following error appears:
**RecreatePanes.js:421 TypeError: Cannot set properties of null (setting 'currentDl')
    at Object.NgChm.DEV.flickChange (DetailHeatMapEvent.js:522:22)
    at setFlickState (RecreatePanes.js:418:15)
    at waitForPlugins (RecreatePanes.js:47:4)**

**Comment by jmelott** [comment]
Fixed in 2.23.2 build 4.
