### ISSUE TITLE
PDF always failing with error.

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/NG-CHM#262]
I tried with multiple maps and PDFs were broken for all of them.

DetailHeatMapManager.js:252 Uncaught ReferenceError: isVisible is not defined
    at Object.anyVisible (DetailHeatMapManager.js:252:3)
    at Object.NgChm.PDF.openPdfPrefs (PdfGenerator.js:34:42)
    at HTMLDivElement.onclick (chm.html:366:95)

**Comment by bmbroom** [comment]
I pushed a simple fix for this to master.
