### ISSUE TITLE
Error in console when selecting using shift-drag to select cells on detail pane.

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/NG-CHM#354]
Testing with deprez1000.ngchm
Difficult to reproduce.

I had 4 panes, summary in top left with detail below.
On right side had two detail panes open side-to-side.
I was shift-dragging near the bottom-right of the rightmost pane when the error occurred.
The bottom left pane was the primary detail pane at that time.

PluginInstanceManager.js:178 Uncaught TypeError: Cannot read properties of undefined (reading 'indexOf')
    at PIM.postSelectionToPlugins (PluginInstanceManager.js:178:25)
    at SRCH.updateLinkoutSelections (SearchManager.js:93:6)
    at DEV.handleSelectDrag (DetailHeatMapEvent.js:739:14)
    at DEV.handleMouseMove (DetailHeatMapEvent.js:658:7)
PIM.postSelectionToPlugins @ PluginInstanceManager.js:178
SRCH.updateLinkoutSelections @ SearchManager.js:93
DEV.handleSelectDrag @ DetailHeatMapEvent.js:739
DEV.handleMouseMove @ DetailHeatMapEvent.js:658

**Comment by jmelott** [comment]
Fixed in v2.23.2 build 4.
