### ISSUE TITLE
Previous button for search throwing error.

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/NG-CHM#361]
To reproduce:
Open map.
Click search pervious (left arrow) button.

It doesn't matter whether you search and find something or not, it always throws the error.

SearchManager.js:675 Uncaught ReferenceError: currentSearchItem is not defined
    at searchPrev (SearchManager.js:675:25)
    at e.onclick (SearchManager.js:40:27)

**Comment by jmelott** [comment]
Still breaking, but different error.

To reproduce:
Open Developer Console in browser.
Open map.  Click "Previous Search Result" (Left Arrow Icon) in search error.
Error in Console:
MatrixManager.js:643 Uncaught TypeError: Cannot read properties of undefined (reading 'toUpperCase')
    at MMGR.HeatMap.getAxisLabels (MatrixManager.js:643:15)
    at findPrevSearchItem (SearchManager.js:722:29)
    at searchPrev (SearchManager.js:707:6)
    at e.onclick (SearchManager.js:55:27)

**Comment by jmelott** [comment]
Fixed in version 2.23.1
