### ISSUE TITLE
Error message in console if switch between plugins before configuration finished.

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/NG-CHM#386]
To reproduce:
Open map.
Open developer's console in browser.
Switch summary panel to 2D Scatterplot.
Leave dialog open and switch panel to 3D scatterplot or PathwayMapper plugin.

Error occurs in console:
PaneControl.js:1166 Error: attempt to remove unknown popup/icon tuple
    at removePopupNearIcon (PaneControl.js:1166:17)
    at PaneControl.js:468:4
    at Array.forEach (<anonymous>)
    at Object.clearExistingDialogs (PaneControl.js:465:74)
    at switchToPlugin (Linkout.js:2796:11)
    at LNK.switchPaneToPlugin [as switcher] (Linkout.js:976:6)
    at PaneControl.js:851:11
    at mi.onclick (PaneControl.js:811:8)

**Comment by jmelott** [comment]
As of v2.23.2 build 4. error message has changed.
New error also occurs if a gear dialog is open and you click on a gear for a different panel.

PaneControl.js:475 Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Document': '# [data-popup-name]' is not a valid selector.
    at Object.clearExistingDialogs (http://qcprludev07.mdanderson.edu:8082/NG-CHM/javascript/PaneControl.js:475:19)
    at removeOpenGearPanels (http://qcprludev07.mdanderson.edu:8082/NG-CHM/javascript/Linkout.js:1694:10)
    at Object.newGearDialog (http://qcprludev07.mdanderson.edu:8082/NG-CHM/javascript/Linkout.js:1685:3)
    at icon.onclick (http://qcprludev07.mdanderson.edu:8082/NG-CHM/javascript/Linkout.js:2912:8)
clearExistingDialogs @ PaneControl.js:475
removeOpenGearPanels @ Linkout.js:1694
newGearDialog @ Linkout.js:1685
icon.onclick @ Linkout.js:2912
three.min.js:186 THREE.WebGLRenderer 106
PaneControl.js:475 Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Document': '# [data-popup-name]' is not a valid selector.
    at Object.clearExistingDialogs (http://qcprludev07.mdanderson.edu:8082/NG-CHM/javascript/PaneControl.js:475:19)
    at removeOpenGearPanels (http://qcprludev07.mdanderson.edu:8082/NG-CHM/javascript/Linkout.js:1694:10)
    at Object.newGearDialog (http://qcprludev07.mdanderson.edu:8082/NG-CHM/javascript/Linkout.js:1685:3)
    at icon.onclick (http://qcprludev07.mdanderson.edu:8082/NG-CHM/javascript/Linkout.js:2912:8)
clearExistingDialogs @ PaneControl.js:475
removeOpenGearPanels @ Linkout.js:1694
newGearDialog @ Linkout.js:1685
icon.onclick @ Linkout.js:2912
