### ISSUE TITLE
"Payload too large" error on ngchm.net when saving a map with a 3D scatterplot.

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/NG-CHM#390]
To reproduce:
Open map https://tcga.ngchm.net//NGCHM/chm.html?map=77b4bc23fdfd8009e8a634b8252f5ed4bd107327&collectionHome=https%3A%2F%2Ftcga.ngchm.net%2F%3Fview%3D0%26p0DiseaseInput%3Dbrca
Open a new panel below the summary panel and set it to a 3D scatterplot.
Highlight 9 row labels in the detail panel.
Use the grab buttons to fill out the three coordinate items on the 3D scatterplot dialog.
Press apply and close buttons on dialog.
Save the map via the hamburger menu.

Map viewer replaced with message that says "Payload Too Large". 

Error appears in console:
sodium.js:1 Uncaught (in promise) RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): ). Build with -s ASSERTIONS=1 for more info.
    at x (sodium.js:1:304371)
    at sodium.js:1:447655

**Comment by jmelott** [comment]
Worked in saved version of map using v 2.23.2 build 4.
