### ISSUE TITLE
Unable to create PDF when Top Items added to both rows and columns

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/NG-CHM#424]
To reproduce
Load Deprez1000 map.  (Also happened with Lake Map)
Open Console.

Click Heat Map Display Properties Gear.
Switch to Rows & Cols tab.

Select 5 rows on detail map and right click and select copy to clipboard.
Copy those row labels to top items text box in the rows section of dialog.

Select 5 columns on detail map and right click and select copy to clipboard.
Copy those column labels to top items text box in the rows section of dialog.

Click apply.

Create PDF from Hamburger menu.

Dialog box pops up telling you there's been an error.

Console displays the following error:

PdfGenerator.js:200 ReferenceError: doc is not defined
    at drawSummaryTopItemLabels (PdfGenerator.js:1451:27)
    at drawSummaryHeatMapPage (PdfGenerator.js:1417:7)
    at PdfGenerator.js:322:3
    at new Promise (<anonymous>)
    at Object.addSummaryPage [as summary] (PdfGenerator.js:321:13)
    at doNextJob (PdfGenerator.js:314:16)
(anonymous) @ PdfGenerator.js:200
Promise.catch (async)
getViewerHeatmapPDF @ PdfGenerator.js:199
document.getElementById.onclick @ PdfGenerator.js:1793

**Comment by jmelott** [comment]
Note: Additional tests show that error will occur if only one axis has top items and if both top items are cleared, then pdf will create as expected.
