### ISSUE TITLE
Create PDF functionality breaks if only Summary Map present.

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/NG-CHM#425]
To reproduce:
Open Deprez1000 map.
Switch left panel (detail panel) to be summary panel.
Leave right panel blank.
Create PDF.
PDF will be created as expected, but following error will appear in the console and afterward will be unable to create a PDF as Create PDF button on dialog will be disabled from then on:

PdfGenerator.js:87 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'canvas')
    at PDF.pdfCancelButton (PdfGenerator.js:87:17)
    at PdfGenerator.js:224:31
    at <anonymous>

**Comment by jmelott** [comment]
The same issue happens if the detail panel is replaced with a 2D scatterplot instead.
