### ISSUE TITLE
Shift-drag when detail at extreme right side of map causes errors in console.

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/NG-CHM#446]
Open any map.
Move detail view area to extreme right location on summary panel.
On detail pane shift-drag near right edge and go over right edge of detail view.

Error appears in console:
PluginInstanceManager.js:175 Uncaught TypeError: Cannot read properties of undefined (reading 'indexOf')
    at PIM.postSelectionToPlugins (PluginInstanceManager.js:175:25)
    at SRCH.updateLinkoutSelections (SearchManager.js:120:6)
    at DEV.handleSelectDrag (DetailHeatMapEvent.js:748:14)
    at DEV.handleMouseMove (DetailHeatMapEvent.js:666:7)

**Comment by jmelott** [comment]
Fixed in version 2.23.2 build 7.
