### ISSUE TITLE
Need to determine when Active WebGL contexts have been lost and reestablish them if looking at a particular map.

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/NG-CHM#471]
WARNING: Too many active WebGL contexts. Oldest context will be lost.
f @ :8080/NGCHM-web-buil…%20GUI%202.21.1:359
d @ :8080/NGCHM-web-buil…%20GUI%202.21.1:361
x.GL.createGlManager @ :8080/NGCHM-web-buil…%20GUI%202.21.1:367
b @ :8080/NGCHM-web-buil…%20GUI%202.21.1:383
m @ :8080/NGCHM-web-buil…%20GUI%202.21.1:859
(anonymous) @ :8080/NGCHM-web-buil…%20GUI%202.21.1:857
Promise.then (async)
G @ :8080/NGCHM-web-buil…%20GUI%202.21.1:854
f @ :8080/NGCHM-web-buil…%20GUI%202.21.1:838
setTimeout (async)
(anonymous) @ :8080/NGCHM-web-buil…%20GUI%202.21.1:838
Promise.then (async)
f @ :8080/NGCHM-web-buil…%20GUI%202.21.1:838
setTimeout (async)
(anonymous) @ :8080/NGCHM-web-buil…%20GUI%202.21.1:839
a @ :8080/NGCHM-web-buil…%20GUI%202.21.1:837
x @ :8080/NGCHM-web-buil…%20GUI%202.21.1:836
document.getElementById.onclick @ :8080/NGCHM-web-buil…%20GUI%202.21.1:896
ColorMapManager.js:333 Uncaught TypeError: Cannot read properties of undefined (reading 'color_map')
    at CMM.ColorMapManager.getColorMap (ColorMapManager.js:333:100)
    at DET.drawDetailHeatMap (DetailHeatMapDisplay.js:213:48)
    at DetailHeatMapDisplay.js:2533:11
getColorMap @ ColorMapManager.js:333
DET.drawDetailHeatMap @ DetailHeatMapDisplay.js:213
(anonymous) @ DetailHeatMapDisplay.js:2533
setTimeout (async)
(anonymous) @ Drawing.js:312

**Comment by bmbroom** [comment]
I'm going to remove the show-stopper label.  If Chris's experiments result in a timely fix, we can include it in the release, but if it's not close to ready I think we should go ahead with the release.
