### ISSUE TITLE
Click-drag in detail panel starting on column covariate and ending in map generates errors in console.

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/NG-CHM#487]
Does not cause error if starting in row covariate area.

Errors:
PluginInstanceManager.js:175 Uncaught TypeError: Cannot read properties of undefined (reading 'indexOf')
    at PIM.postSelectionToPlugins (PluginInstanceManager.js:175:25)
    at SRCH.updateLinkoutSelections (SearchManager.js:121:6)
    at DEV.handleSelectDrag (DetailHeatMapEvent.js:754:14)
    at DEV.handleMouseMove (DetailHeatMapEvent.js:672:7)
PIM.postSelectionToPlugins @ PluginInstanceManager.js:175
SRCH.updateLinkoutSelections @ SearchManager.js:121
DEV.handleSelectDrag @ DetailHeatMapEvent.js:754
DEV.handleMouseMove @ DetailHeatMapEvent.js:672

**Comment by bmbroom** [comment]
I cannot replicate.
